ALTER RESOURCE POOL "default"
WITH
     ( CAP_CPU_PERCENT = 10)
GO
ALTER RESOURCE GOVERNOR RECONFIGURE
GO

-- Go back to default
ALTER RESOURCE POOL "default"
WITH
     ( CAP_CPU_PERCENT = 100)
GO
ALTER RESOURCE GOVERNOR RECONFIGURE
GO

