CREATE EVENT SESSION [memory_tracing] ON SERVER 
ADD EVENT sqlos.page_allocated(
    ACTION(sqlserver.sql_text)
    WHERE ([memory_clerk_name]=N'CACHESTORE_SQLCP')),
ADD EVENT sqlos.page_freed(
    ACTION(sqlserver.sql_text)
    WHERE ([memory_clerk_name]=N'CACHESTORE_SQLCP'))
WITH (MAX_MEMORY=20480 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=1 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=PER_CPU,TRACK_CAUSALITY=OFF,STARTUP_STATE=OFF)
GO


